x-common: &common
  restart: unless-stopped
  deploy:
    resources:
      limits:
        cpus: '0.25'
        memory: 256M

services:
  nginx:
    !!merge <<: *common
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  kafka:
    !!merge <<: *common
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_NUM_PARTITIONS: 3
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
      interval: 60s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  kafka-ui:
    !!merge <<: *common
    image: ghcr.io/kafbat/kafka-ui:db7cc80
    container_name: kafbat-ui
    ports:
      - "13700:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      kafka:
        condition: service_healthy

  ingestion-1:
    !!merge <<: *common
    build:
      context: ..
      dockerfile: ./docker/location/Dockerfile
    container_name: ingestion
    environment:
      INGESTION_OTEL_SERVICE_NAME: github.com/tuanta7/k6noz/services/ingestion
      INGESTION_BIND_ADDRESS: 0.0.0.0:8080

  ingestion-2:
    !!merge <<: *common
    build:
      context: ..
      dockerfile: ./docker/location/Dockerfile
    container_name: ingestion
    environment:
      INGESTION_OTEL_SERVICE_NAME: github.com/tuanta7/k6noz/services/ingestion
      INGESTION_BIND_ADDRESS: 0.0.0.0:8080


  driver:
    !!merge <<: *common
    build:
      context: ..
      dockerfile: ./docker/driver/Dockerfile
    container_name: driver
    environment:
      OTEL_GRPC_ENDPOINT: host.docker.internal:4317
      DRIVER_OTEL_SERVICE_NAME: github.com/tuanta7/k6noz/services/driver
      DRIVER_BIND_ADDRESS: 0.0.0.0:8080
      DRIVER_MONGO_URI: mongodb://host.docker.internal:27017
      DRIVER_MONGO_DATABASE: k6noz